---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs

inputs:
- name: buildpack-mgmt-pipelines

params:
  CF_API_URI:
  CF_USERNAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  BUILDPACK_NAME:
  APP_NAME:

run:
  path: buildpack-mgmt-pipelines/tasks/validate-app/task.sh