---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.28


inputs:
- name: pcf-pipelines

params:
  CF_API_URI:
  CF_USERNAME:
  CF_PASSWORD:
  SOURCE_BUILDPACK_NAME:
  TARGET_BUILDPACK_NAME:
  STACKS:

run:
  path: pcf-pipelines/tasks/promote-buildpack/task.sh
