groups:
- name: download_buildpack
  jobs:
  - regulator
- name: update_buildpack
  jobs:
  - trigger-buildpack-update

resource_types:
- name: pivnet
  type: docker-image
  source:
    repository: pivotalcf/pivnet-resource
    tag: latest-final

- name: rocketchat
  type: docker-image
  source:
    repository: michaellihs/rocket-notify-resource

resources:
- name:  buildpack-mgmt-pipelines
  type: git
  icon: github-circle
  source:
    uri: ((buildpack-mgmt-pipelines-url))
    branch: master
    username: ((git-username))
    password: ((git-password))
    skip_ssl_verification: true

- name: buildpack-mgmt-cmdb
  type: git
  icon: github-circle
  source:
    uri: ((buildpack-mgmt-cmdb-url))
    branch: master
    username: ((git-username))
    password: ((git-password))
    skip_ssl_verification: true

- name: rocketchat
  type: rocketchat
  icon: chat
  source:
    url: ((rocket-chat-url))
    user: ((rocket-chat-username))
    password: ((rocket-chat-password))

jobs:
- name: trigger-buildpack-update
  serial_groups: [cc-api]
  plan:
  - in_parallel:
    - get: buildpack-mgmt-cmdb
      trigger: true
    - get: buildpack-mgmt-pipelines
  - task: cmdb-trigger-buildpack-update
    file: buildpack-mgmt-pipelines/tasks/trigger-update/task.yml
    params:
      FLY_HOST: ((fly-host))
      FLY_TEAM: ((fly-team))
      FLY_USERNAME: ((fly-username))
      FLY_PASSWORD: ((fly-password))
      CF_API_URI: ((cf-api-uri))
      CF_USERNAME: ((cf-username))
      CF_PASSWORD: ((cf-password))
      PIPELINE: ((pipeline))
