platform: linux
image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
inputs:
- name: buildpack-mgmt-pipelines
- name: buildpack-mgmt-cmdb

run:
  path: buildpack-mgmt-pipelines/tasks/trigger-update/task.sh
params:
  FLY_HOST:
  FLY_TEAM:
  FLY_USERNAME:
  FLY_PASSWORD:
  CF_API_URI:
  CF_USERNAME:
  CF_PASSWORD:
  PIPELINE:
